version: "3.6"
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: ${MB_DB_TYPE}
      MB_DB_DBNAME: ${MB_DB_DBNAME}
      MB_DB_PORT: ${MB_DB_PORT}
      MB_DB_USER: ${MB_DB_USER}
      MB_DB_PASS: ${MB_DB_PASS}
      MB_DB_HOST: ${MB_DB_HOST}
      MB_SITE_URL: http://10.0.1.9:3000/
