version: "3.6"
services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    ports:
      - 3001:3000
    volumes:
      - ./metabase_data:/metabase-data
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: metabase@cfr-azu-db01
      MB_DB_PASS: metabase
      MB_DB_HOST: cfr-azu-db01.postgres.database.azure.com
      MB_SITE_URL: http://10.0.1.9:3000/
